server:
    port: 8080
spring:
    application:
        name: kafka-demo
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            enable-auto-commit: true
            group-id: consumer1
            # 批量消费每次最多消费多少条消息
            max-poll-records: 50
        listener:
            missing-topics-fatal: false
            # 批量消费
            type: single
        producer:
            properties:
                # 配置自定义消息分发策略
                partitioner.class: com.zengdw.kafka.config.MyPartition