server:
  port: 9002
  servlet:
    session:
      cookie:
        name: resource

security:
  oauth2:
    resource:
      id: resource
      token-info-uri: http://127.0.0.1:9000/oauth/check_token
    client:
      client-id: client2
      client-secret: secret2

logging:
  level:
    org:
      springframework:
        security: debug

spring:
  main:
    allow-bean-definition-overriding: true