server:
  port: 9001
  servlet:
    session:
      cookie:
        name: client1

security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      access-token-uri: http://127.0.0.1:9000/oauth/token
      user-authorization-uri: http://127.0.0.1:9000/oauth/authorize
    resource:
      token-info-uri: http://127.0.0.1:9000/oauth/check_token

logging:
  level:
    org:
      springframework:
        security: debug